apiVersion: v1
kind: Pod
metadata:
  name: infra-discovery
  labels:
    env: dev
    app: infra-discovery
spec:
  initContainers:
    - name: init-infra-discovery
      image: localhost:31320/discovery-config:latest
      command: [bash, -c]
      args: ["cp -r /config/* /data"]
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: /data
        name: cache-volume
  containers:
    - name: infra-discovery
      image: localhost:31320/infra-discovery:latest
      ports:
        - name: infra-discovery
          containerPort: 8761
          protocol: TCP
      envFrom:
      - configMapRef:
          name: ife-config
      volumeMounts:
      - mountPath: /home/config
        name: cache-volume
        readOnly: true
  volumes:
  - name: cache-volume
    emptyDir: {}