apiVersion: v1
kind: Pod
metadata:
  name: infra-discovery
  labels:
    env: dev
    app: infra-discovery
spec:
  containers:
    - name: infra-discovery
      image: localhost:31320/infra-discovery:latest
      ports:
        - name: infra-discovery
          containerPort: 8761
          protocol: TCP
      envFrom:
      - configMapRef:
          name: game-config
      volumeMounts:
      - mountPath: /home/config
        name: config
      - mountPath: /home/jar
        name: jar
  volumes:
  - name: jar
    hostPath:
      # directory location on host
      path: /home/deploy/infra-discovery/jar
      # this field is optional
      type: Directory
  - name: config
    hostPath:
      # directory location on host
      path: /home/deploy/infra-discovery/config
      # this field is optional
      type: Directory
