apiVersion: v1
kind: Service
metadata:
  name: infra-discovery
spec:
  selector:
    app: infra-discovery
  type: ClusterIP
  externalIPs:
  - 192.168.226.133
  - 192.168.226.134
  ports:
  - port: 8761
    targetPort: 8761
    protocol: TCP
    name: infra-discovery
  selector:
    app: infra-discovery