apiVersion: v1
kind: Service
metadata:
  name: infra-discovery
spec:
  selector:
    app: infra-discovery
  type: LoadBalancer
  externalIPs:
  - 192.168.226.133
  - 192.168.226.134
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
