apiVersion: v1
kind: Pod
metadata:
  name: fe
  labels:
    name: fe
spec:
  serviceAccountName: test
  containers:
  - name: fe
    image: minhquan0107/test
    ports:
    - containerPort: 3000
      name: http
      protocol: TCP
---