{{- if .Values.elasticsearch.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{template "elasticsearch.name" . }}
  namespace: {{ template "elasticsearch.namespace" . }}
  annotations:
{{ toYaml .Values.elasticsearch.ingress.annotations | indent 4 }}
spec:
  tls:
  - hosts:
    - {{.Values.elasticsearch.ingress.host}}
    secretName: {{template "elasticsearch.name" . }}
  rules:
    - host: {{.Values.elasticsearch.ingress.host}}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{template "elasticsearch.client" . }}
            servicePort: {{.Values.elasticsearch.clientPort}}
{{- end }}