apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameapi }}
spec:
  selector:
    {{- include "test.label" . | indent 4 }}
  type: ClusterIP
  externalIPs:
  - {{ .Values.IP }}
  ports:
  - port: {{ .Values.portapi }}
    targetPort: {{ .Values.targetportapi }}
    protocol: TCP
    name: {{ .Values.nameapi }}
  selector:
    {{- include "test.label" . | indent 4 }}