apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
    app: nginx
  type: LoadBalancer
  externalIPs:
  - 192.168.226.133
  - 192.168.226.134
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
