apiVersion: v1
kind: Service
metadata:
  name: infra-api-manager
spec:
  selector:
    app: infra-api-manager
  type: ClusterIP
  externalIPs:
  - 192.168.226.133
  - 192.168.226.134
  ports:
  - port: 2407
    targetPort: 2407
    protocol: TCP
    name: api-manager
  selector:
    app: infra-api-manager