apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    {{- include "test.labels" . | indent 4 }}
  type: ClusterIP
  externalIPs:
  - {{ .Values.IP }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.targetport }}
    protocol: TCP
    name: {{ .Values.name }}
  selector:
    {{- include "test.labels" . | indent 4 }}