apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    env: dev
    app: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: minhquan0107/udagram-reverseproxy:latest
        imagePullPolicy: Always
        ports:
        - name: reverseproxy
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m    
---
apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
spec:
  selector:
    app: reverseproxy
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: reverseproxy
  selector:
    app: reverseproxy
